name = "FiniteHorizonPOMDPs"
uuid = "8a13bbfe-798e-11e9-2f1c-eba9ee5ef093"
authors = ["Tomas Omasta <omastto1@fel.cvut.cz> and contributors"]
version = "0.1.0"

[deps]
POMDPLinter = "f3bd98c0-eb40-45e2-9eb1-f2763262d755"
POMDPModelTools = "08074719-1b2a-587c-a292-00f91cc44415"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"

[compat]
POMDPLinter = "0.1"
POMDPModelTools = "0.3"
POMDPs = "0.9"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
